#you can use static_libs=1/0 ,to build static lib or dynamiclib
MYLIBNAME=BNGEvent
MYFILES = \
CEventReactor.cpp

MYCPPFLAGS= -I../include -std=gnu++11
MYLDFLAGS=
MYDLLLIB=
include $(ACE_ROOT)/include/makeinclude/templatemakefile.GNU

