/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-02-10 07:59:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write('\n');

String portalPath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+"/";


      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\"/>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("    <title>登录</title>\n");
      out.write("    <meta http-equiv=\"pragma\" content=\"no-cache\"/>\n");
      out.write("    <meta http-equiv=\"cache-control\" content=\"no-cache\"/>\n");
      out.write("    <meta http-equiv=\"expires\" content=\"0\"/>\n");
      out.write("    <meta http-equiv=\"keywords\" content=\"Open Portal\"/>\n");
      out.write("    <meta http-equiv=\"description\" content=\"Open Portal login\"/>\n");
      out.write("    <link type=\"text/css\" href=\"css/index.css\" rel=\"stylesheet\" />\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("function _change() {\n");
      out.write("\t/*\n");
      out.write("\t1. 得到img元素\n");
      out.write("\t2. 修改其src为/day11_3/VerifyCodeServlet\n");
      out.write("\t*/\n");
      out.write("\tvar imgEle = document.getElementById(\"img\");\n");
      out.write("\timgEle.src = \"");
      out.print(path);
      out.write("/VCodeServlet?a=\" + new Date().getTime();\n");
      out.write("}\n");
      out.write("function _submit() {\n");
      out.write("\t/*\n");
      out.write("\t1. 得到img元素\n");
      out.write("\t2. 修改其src为/day11_3/VerifyCodeServlet\n");
      out.write("\t*/\n");
      out.write("\tdocument.getElementById(\"msg\").innerHTML = \"正在请求认证，请稍等....\";\n");
      out.write("\tdocument.getElementById(\"Submit\").disabled=true;\n");
      out.write("\treturn true;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\t\n");
      out.write("</head>\n");
 
  String username=(String)session.getAttribute("username");
  String ip=(String)session.getAttribute("ip");
  if(username!=null&&ip!=null){
  	request.getRequestDispatcher("/loginSucc.jsp").forward(request, response);
  	return;
  }else{
  
      out.write('\n');
      out.write('	');

    String uname="";
    Cookie[] cs=request.getCookies();
    if(cs!=null){
    	for(Cookie c:cs){
    		if("uname".equals(c.getName())){
    			uname=c.getValue();
    		}
    		
    	}
    }
    
    
    String message="";
    String msg=(String)request.getAttribute("msg");
    if(msg!=null){
    	message=msg;
    }
    
      out.write("\n");
      out.write("<body>\n");
      out.write("    <div id=\"page-content\">\n");
      out.write("        <div id=\"login-page\">\n");
      out.write("            <div id=\"logo\">\n");
      out.write("                <a href=\"");
      out.print(basePath);
      out.write("\"><img alt=\"LaterThis\" src=\"images/logo.png\" /></a>\n");
      out.write("            </div>\n");
      out.write("           \n");
      out.write("  \n");
      out.write("            <form id=\"loginForm\" action=\"");
      out.print(path);
      out.write("/Login\" method=\"post\" onsubmit=\"_submit()\">\n");
      out.write("                <div id=\"normal-login\">\n");
      out.write("                    <p>\n");
      out.write("                        <label style=\"text-align: center ;\"><font color=\"red\"><b id=\"msg\">");
      out.print(message);
      out.write("</b></font></label> <br/>\n");
      out.write("                    </p>\n");
      out.write("                    <p style=\"padding-top:5px;\">\n");
      out.write("                        <label for=\"username\">用户名</label> <br/>\n");
      out.write("                        <input id=\"username\" name=\"username\" value=\"");
      out.print(uname);
      out.write("\" />\n");
      out.write("                    </p>\n");
      out.write("                    <p>\n");
      out.write("                        <label for=\"password\">密码</label> <br/> \n");
      out.write("                        <input id=\"password\" type=\"password\" name=\"password\" value=\"\" />\n");
      out.write("                    </p>\n");
      out.write("                    <p>\n");
      out.write("                        <label for=\"password\">验证码</label> <br/> \n");
      out.write("                        <input id=\"vcode\"  name=\"vcode\" value=\"\" size=\"4\" />        <img id=\"img\" alt=\"请输入验证码\"\n");
      out.write("\t\t\tsrc=\"");
      out.print(path);
      out.write("/VCodeServlet\" /><a href=\"javascript:_change()\">      换一张</a><br />\n");
      out.write("                    </p>\n");
      out.write("\t                <p>\n");
      out.write("\t                    <input id=\"Submit\" class=\"button\" type=\"submit\" value=\"登录\" name=\"commit\" />\n");
      out.write("\t                    <span style=\"padding:5px;\"></span>\n");
      out.write("\t                    <input class=\"button\" type=\"reset\" value=\"重置\" name=\"reset\"/>\n");
      out.write("\t                </p>\n");
      out.write("                </div>\n");
      out.write("               </form>\n");
      out.write("                <p id=\"signup\">\n");
      out.write("                   Copyright &copy; 2014 - 2015 <a href=\"");
      out.print(basePath);
      out.write("\">OpenPortal Server-李硕</a>.  All Rights Reserved.\n");
      out.write("               </p>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
} 
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
